<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #00FFFF;        
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Moin Moin zur  <span id="zf-name">Zend Framework!</span> Schulung</h1>

    <h3>Dies ist die erste seite</h3>

    <div id="more-information">       
        <p>
            ZF Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>